version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-egames
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mi-contraseña
      MYSQL_DATABASE: egamesSQL
    ports:
      - 3311:3306
    volumes:
      - "./docker/mysql/1egames.sql:/docker-entrypoint-initdb.d/1egames.sql"
      - "./docker/mysql/2egamesInsertData.sql:/docker-entrypoint-initdb.d/2egamesInsertData.sql"
      - "./docker/mysql/3egamesStockData.sql:/docker-entrypoint-initdb.d/3egamesStockData.sql"
      - ~/egamesData/mysql:/var/lib/mysql
    networks:
      - egames
  node:
    build: .
    container_name: node-egames
    restart: always
    ports:
      - 3011:3000
    depends_on:
      - mysql
    networks:
      - egames
    volumes:
      - ./:/usr/src/app
      - exclude:/usr/src/app/node_modules/
volumes:
  exclude:
networks:
  egames:
