version: "3"
services:
  mysql:
    image: mysql:5.6
    container_name: mysql-egames
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mi-contraseña
      MYSQL_DATABASE: egames
    ports:
      - 3311:3306
    volumes:
      - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./docker/mysql/1egames.sql:/docker-entrypoint-initdb.d/1egames.sql"
      - "./docker/mysql/2egamesInsertData.sql:/docker-entrypoint-initdb.d/2egamesInsertData.sql"
      - "./docker/mysql/3egamesStockData.sql:/docker-entrypoint-initdb.d/3egamesStockData.sql"
      - ~/egamesData/mysql:/var/lib/mysql
    networks:
      - egames
  node:
    build: ./back
    container_name: node-egames
    restart: always
    ports:
      - 3011:3000
    depends_on:
      - mysql
    networks:
      - egames
    volumes:
      - ./back:/usr/src/app
      - exclude:/usr/src/app/node_modules/
  react:
    build: ./front
    container_name: react-egames
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - node
    networks:
      - egames
    volumes:
      - ./front:/usr/src/app
volumes:
  exclude:
networks:
  egames:
